openapi: 3.1.0
info:
  title: 認証
  description: |-
    仮実装
  version: '0.1'
servers:
  - url: 'https://bizdevforge-backphp.dev.dsbizdev.com/v1'
    description: プロトタイプ環境
paths:
  /auth/login:
    post:
      summary: ログイン
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  required: true
                password:
                  type: string
                  required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        '400':
          $ref: 'components/error_response.yaml#/components/responses/BadRequest'
        '401':
          $ref: 'components/error_response.yaml#/components/responses/UserIncorrectException'
        '423':
          $ref: 'components/error_response.yaml#/components/responses/Locked'
        '500':
          $ref: 'components/error_response.yaml#/components/responses/InternalServerError'
  /auth/logout:
    get:
      summary: ログアウト
      responses:
        '204':
          description: OK
        '400':
          $ref: 'components/error_response.yaml#/components/responses/BadRequest'
        '401':
          $ref: 'components/error_response.yaml#/components/responses/UnauthorizedError'
        '500':
          $ref: 'components/error_response.yaml#/components/responses/InternalServerError'
      security:
        - UserAuth: []

components:
  securitySchemes:
    UserAuth:
      $ref: 'components/security_schemes.yaml#/components/securitySchemes/BearerAuth'
