openapi: 3.1.0
info:
  title: デジタルバックオフィスAPI
  description: |-
    外部システム向けAPI
  version: '1.0.0'
servers:
  - url: 'https://dbo-dd.dev.dsbizdev.com/v1'
    description: ステージング環境
paths:
  /external/service-contracts/{public_id}/invoice-info:
    get:
      summary: 請求情報 取得
      parameters:
        - $ref: 'components/parameters.yaml#/components/parameters/ExternalAuthenticationKey'
        - name: public_id
          in: path
          description: サービス契約UUID
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/ServiceContractsInvoiceInfoGetRequest'
        '401':
          $ref: 'components/error_response.yaml#/components/responses/UnauthorizedError'
        '403':
          $ref: 'components/error_response.yaml#/components/responses/Forbidden'
        '404':
          $ref: 'components/error_response.yaml#/components/responses/NotFound'
        '500':
          $ref: 'components/error_response.yaml#/components/responses/InternalServerError'

components:
  schemas:
    ServiceContractsInvoiceInfoGetRequest:
      description: 請求情報
      type: object
      properties:
        serviceContractPublicId:
          type: string
          format: uuid
          description: サービス契約UUID
        sender:
          type: object
          description: 請求元情報
          properties:
            salesRepCompanyName:
              type: string
              description: サービス担当者 会社名
            salesRepName:
              type: string
              description: サービス担当者 氏名
            salesRepEmail:
              type: string
              description: サービス担当者 メールアドレス
            salesRepPhoneNumber:
              type: string
              description: サービス担当者 電話番号
            salesRepManagerCompanyName:
              type: string
              description: サービス管理者 会社名
            salesRepManagerName:
              type: string
              description: サービス管理者 氏名
            salesRepManagerEmail:
              type: string
              description: サービス管理者 メールアドレス
            salesRepManagerPhoneNumber:
              type: string
              description: サービス管理者 電話番号
            serviceDeptGroupEmail:
              type: string
              description: サービス部署メールアドレス
            backofficeGroupEmail:
              type: string
              description: バックオフィス部署メールアドレス
        recipient:
          type: object
          description: 請求先情報
          properties:
            userName:
              type: string
              description: 顧客側支払担当者氏名
            userDept:
              type: string
              description: 顧客側支払担当者部署
            userTitle:
              type: string
              description: 顧客側支払担当者役職
            userEmail:
              type: string
              description: 顧客側支払担当者メール
