openapi: 3.1.0
info:
  title: デジタルバックオフィスAPI
  description: |-
    認証不要エンドポイント郡
  version: '1.0.0'
servers:
  - url: 'https://dbo-dd.dev.dsbizdev.com/v1'
    description: ステージング環境
paths:
  /country-regions:
    get:
      summary: 国・地域 取得
      parameters:
        - $ref: 'components/parameters.yaml#/components/parameters/AcceptLanguage'
        - name: countryCodeAlpha3
          in: query
          required: false
          schema:
            type: string
        - name: countryCodeAlpha2
          in: query
          required: false
          schema:
            type: string
        - name: countryCodeNumeric
          in: query
          required: false
          schema:
            type: integer
        - $ref: 'components/parameters.yaml#/components/parameters/DisplayPageNumber'
        - $ref: 'components/parameters.yaml#/components/parameters/DisplayedResults'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/CountryRegionResponse'
                  'links':
                    $ref: 'components/pagination.yaml#/components/schemas/PaginationLinks'
                  'meta':
                    $ref: 'components/pagination.yaml#/components/schemas/PaginationMeta'
        '422':
          $ref: 'components/error_response.yaml#/components/responses/UnprocessableEntity'
        '500':
          $ref: 'components/error_response.yaml#/components/responses/InternalServerError'
  /misc-data:
    get:
      summary: 汎用テーブル選択肢 取得
      parameters:
        - $ref: 'components/parameters.yaml#/components/parameters/AcceptLanguage'
        - name: type
          description: 選択肢アイテムコード
          in: query
          required: true
          schema:
            type: string
          examples:
            PaymentMethod:
              summary: 支払い方法
              value: payment_method
            PaymentCycle:
              summary: 支払いサイクル
              value: payment_cycle
            WorldRegion:
              summary: 世界地域
              value: world_region
            LanguageCode:
              summary: 言語コード
              value: language_code
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/MiscDataResponse'
        '422':
          $ref: 'components/error_response.yaml#/components/responses/UnprocessableEntity'
        '500':
          $ref: 'components/error_response.yaml#/components/responses/InternalServerError'

components:
  schemas:
    CountryRegionResponse:
      description: 国・地域
      type: object
      properties:
        countryCodeAlpha3:
          type: string
          description: '国コード（ISO 3166-1 alpha-3）'
          example: JPN
        countryCodeAlpha2:
          type: string
          description: '国コード（ISO 3166-1 alpha-2）'
          example: JP
        countryCodeNumeric:
          type: integer
          description: '国コード（ISO 3166-1 numeric）'
          example: 392
        worldRegion:
          type: string
          description: 対象言語に翻訳された世界地域
          example: 日本
        countryRegionName:
          type: string
          description: 対象言語に翻訳された国・地域名称
          example: 日本国
        capitalName:
          type: string
          description: 対象言語に翻訳された首都名称
          example: 東京
    MiscDataResponse:
      description: 選択肢
      type: object
      properties:
        selectionItemType:
          type: string
          description: '選択肢アイテム種別（typeで指定した値）'
        selectionItemCode:
          type: string
          description: 選択肢アイテムコード
        selectionItemName:
          type: string
          description: 選択肢アイテム名称
        selectionItemShortName:
          type: string
          description: 選択肢アイテム短縮名称
