<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('time_zones', function (Blueprint $table) {
            $table->comment('タイムゾーンテーブル');

            // システム識別子
            $table->unsignedBigInteger('time_zone_id')
                ->primary()
                ->comment('内部用連番 PK');

            // 属性
            $table->text('tz_name')->unique()->comment('IANA タイムゾーン識別子');
            // INTERVAL型はLaravelで直接定義できないため後述で追加
            $table->text('display_label')->comment('UI 表示用ラベル');
            $table->string('remarks')->nullable()->comment('備考');

            // 監査
            $table->timestamp('created_at')->useCurrent()->comment('作成日時');
            $table->timestamp('updated_at')->useCurrent()->comment('更新日時');
            $table->timestamp('deleted_at')->nullable()->comment('削除日時');
        });

        // ID列にIDENTITYを追加する
        DB::statement("ALTER TABLE time_zones ALTER COLUMN time_zone_id ADD GENERATED BY DEFAULT AS IDENTITY");
        // INTERVAL型カラムとチェック制約を SQL 経由で追加
        DB::statement("ALTER TABLE time_zones ADD COLUMN utc_offset INTERVAL NOT NULL");
        DB::statement("COMMENT ON COLUMN time_zones.utc_offset IS '標準時の UTC オフセット'");
        DB::statement("ALTER TABLE time_zones ADD CONSTRAINT chk_utc_offset CHECK (utc_offset BETWEEN INTERVAL '-12 hours' AND INTERVAL '+14 hours')");
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('time_zones');
    }
};
