<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('address_format_rules', function (Blueprint $table) {
            $table->comment('国・地域別の住所フォーマットテンプレートを管理する');

            // システム識別子
            $table->unsignedBigInteger('address_format_rule_id')
                ->primary()
                ->comment('内部用連番 PK');

            // ビジネス識別子
            $table->char('country_code_alpha3', 3)
                ->unique()
                ->comment('国コード (ISO-3166-1 alpha-3、例: JPN)');

            // 必須属性
            $table->text('format_string')
                ->comment('住所表示テンプレート（{{postal}} {{state}}{{city}} … 形式）');

            // 任意属性
            $table->string('remarks')->nullable()
                ->comment('テンプレートに関する備考');

            // 監査系
            $table->timestamp('created_at')->useCurrent()
                ->comment('レコード作成日時');
            $table->timestamp('updated_at')->useCurrent()
                ->comment('レコード更新日時');
            $table->timestamp('deleted_at')->nullable()
                ->comment('レコード削除日時');

            // 外部キー
            $table->foreign('country_code_alpha3')
                ->references('country_code_alpha3')
                ->on('country_regions')
                ->onUpdate('cascade')
                ->onDelete('cascade');
        });

        // ID列にIDENTITYを追加する
        DB::statement("ALTER TABLE address_format_rules ALTER COLUMN address_format_rule_id ADD GENERATED BY DEFAULT AS IDENTITY");
        // パーシャルインデックス（論理削除されていない行のみ）
        DB::statement("CREATE INDEX idx_addr_fmt_deleted_null ON address_format_rules (country_code_alpha3) WHERE deleted_at IS NULL");
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('address_format_rules');
    }
};
