<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('country_regions_translations', function (Blueprint $table) {
            $table->comment('国・地域の翻訳情報を管理する');

            // システム識別子
            $table->unsignedBigInteger('country_region_translation_id')
                ->primary()
                ->comment('内部用連番 PK');

            // ビジネス識別子
            $table->char('country_code_alpha3', 3)
                ->comment('国コード (ISO 3166-1 alpha-3、例: JPN)');
            $table->char('language_code', 3)
                ->comment('言語コード (ISO 639-3)。例: eng, jpn, ind, tha, cmn, yue)');

            // 必須属性
            $table->string('world_region')
                ->comment('翻訳済み世界地域名');
            $table->string('country_region_name')
                ->comment('翻訳済み国・地域名称');

            // 任意属性
            $table->string('capital_name')->nullable()
                ->comment('翻訳済み首都名称 (任意)');
            $table->string('remarks')->nullable()
                ->comment('翻訳や言語情報に関する備考');

            // 監査系
            $table->timestamp('created_at')->useCurrent()
                ->comment('レコード作成日時');
            $table->timestamp('updated_at')->useCurrent()
                ->comment('レコード更新日時');
            $table->timestamp('deleted_at')->nullable()
                ->comment('レコード削除日時 (論理削除)');

            // 複合ユニーク制約
            $table->unique(['country_code_alpha3', 'language_code']);

            // 外部キー
            $table->foreign('country_code_alpha3')
                ->references('country_code_alpha3')
                ->on('country_regions')
                ->onUpdate('cascade')
                ->onDelete('restrict');

            // インデックス
            $table->index('language_code');
        });

        // ID列にIDENTITYを追加する
        DB::statement("ALTER TABLE country_regions_translations ALTER COLUMN country_region_translation_id ADD GENERATED BY DEFAULT AS IDENTITY");
        // パーシャルインデックス（WHERE deleted_at IS NULL）
        DB::statement("CREATE INDEX idx_country_region_translations_deleted_null ON country_regions_translations (country_code_alpha3, language_code) WHERE deleted_at IS NULL");
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('country_regions_translations');
    }
};
