<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('country_field_display_orders', function (Blueprint $table) {
            $table->comment('国・地域別の住所フォーマットテンプレートを管理する');

            // システム識別子
            $table->unsignedBigInteger('country_field_display_order_id')
                ->primary()
                ->comment('内部用連番 PK');

            // ビジネス識別子
            $table->char('country_code_alpha3', 3)
                ->unique()
                ->comment('国コード (ISO-3166-1 alpha-3、例: JPN)');

            // 属性
            $table->text('name_fields_order')
                ->comment('氏名表示順序（{{lastname}} {{middlename}} {{firstname}} … 形式）');
            $table->text('address_fields_order')
                ->comment('住所表示順序（{{postal}} {{state}}{{city}} … 形式）');
            $table->text('remarks')->nullable()
                ->comment('テンプレートに関する備考');

            // 監査系
            $table->timestamp('created_at')->useCurrent()
                ->comment('レコード作成日時');
            $table->timestamp('updated_at')->useCurrent()
                ->comment('レコード更新日時');
            $table->timestamp('deleted_at')->nullable()
                ->comment('レコード削除日時');

            // 外部キー
            $table->foreign('country_code_alpha3')
                ->references('country_code_alpha3')
                ->on('country_regions')
                ->onUpdate('cascade')
                ->onDelete('cascade');
        });

        // ID列にIDENTITYを追加する
        DB::statement("ALTER TABLE country_field_display_orders ALTER COLUMN country_field_display_order_id ADD GENERATED BY DEFAULT AS IDENTITY");
        // パーシャルインデックス（論理削除されていない行のみ）
        DB::statement("CREATE INDEX idx_addr_fmt_deleted_null ON country_field_display_orders (country_code_alpha3) WHERE deleted_at IS NULL");
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('country_field_display_orders');
    }
};
