<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('selection_items', function (Blueprint $table) {
            $table->comment('選択肢アイテム情報を管理する');

            // システム識別子
            $table->unsignedBigInteger('selection_item_id')
                ->primary()
                ->comment('内部用連番 PK');

            // ビジネス識別子
            $table->string('selection_item_type')
                ->comment('選択肢アイテムの種類を示す文字列');
            $table->string('selection_item_code')
                ->comment('選択肢アイテムを識別する文字列');

            // 属性
            $table->integer('display_order')
                ->comment('ドロップダウンリストでの表示順序');
            $table->string('remarks')->nullable()
                ->comment('ステータスに関する備考・補足情報');

            // 監査系（作成・更新・論理削除）
            $table->timestamp('created_at')->useCurrent()
                ->comment('レコードが作成された日時');
            $table->timestamp('updated_at')->useCurrent()
                ->comment('レコードが更新された日時');
            $table->timestamp('deleted_at')->nullable()
                ->comment('レコードが削除された日時');

            // 複合ユニーク制約
            $table->unique(['selection_item_type', 'selection_item_code']);

            // インデックス
            $table->index('selection_item_type');
        });

        // ID列にIDENTITYを追加する
        DB::statement("ALTER TABLE selection_items ALTER COLUMN selection_item_id ADD GENERATED BY DEFAULT AS IDENTITY");
        // パーシャルインデックス（論理削除されていない行のみ）
        DB::statement('CREATE INDEX idx_selection_items_deleted_null ON selection_items(selection_item_type, selection_item_code) WHERE deleted_at IS NULL');
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('selection_items');
    }
};
