<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('contract_widget_settings', function (Blueprint $table) {
            $table->comment('契約書ウィジェット設定テーブル');

            // システム識別子
            $table->unsignedBigInteger('contract_widget_setting_id')
                ->primary()
                ->comment('内部連番（PK）');

            // ビジネス識別子
            $table->uuid('public_id')
                ->unique()
                ->default(DB::raw('gen_random_uuid()'))
                ->comment('外部公開用 UUID v4');

            // 属性
            $table->unsignedBigInteger('tenant_id')->comment('所属テナントID');
            $table->unsignedBigInteger('service_id')->comment('サービスID');
            $table->unsignedBigInteger('service_plan_id')->comment('サービスプランID');

            $table->string('contract_template_id')->comment('契約書テンプレートID');
            $table->char('contract_language', 3)->comment('契約書言語');

            $table->string('widget_name')->comment('ウィジェット名称');
            $table->string('widget_type')->comment('ウィジェット種別');
            $table->string('widget_source_table')->comment('ウィジェットソーステーブル');
            $table->string('widget_source_column')->comment('ウィジェットソース項目');

            $table->integer('widget_x_coord')->comment('ウィジェット X 座標');
            $table->integer('widget_y_coord')->comment('ウィジェット Y 座標');
            $table->integer('widget_width')->comment('ウィジェット幅');
            $table->integer('widget_height')->comment('ウィジェット高さ');

            $table->text('remarks')->nullable()->comment('備考');

            $table->timestamp('created_at')->useCurrent()->comment('レコード作成日時');
            $table->timestamp('updated_at')->useCurrent()->comment('レコード更新日時');
            $table->timestamp('deleted_at')->nullable()->comment('レコード削除日時');

            // インデックス
            $table->index(['tenant_id', 'service_id', 'service_plan_id', 'contract_language', 'deleted_at']);
        });

        // ID列にIDENTITYを追加する
        DB::statement("ALTER TABLE contract_widget_settings ALTER COLUMN contract_widget_setting_id ADD GENERATED BY DEFAULT AS IDENTITY");
        // CHECK制約（widget_type の選択肢）
        DB::statement("ALTER TABLE contract_widget_settings ADD CONSTRAINT chk_widget_type_code CHECK (widget_type IN ('DATE', 'DATETIME', 'CURRENCY', 'STRING'))");
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('contract_widget_settings');
    }
};
