<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('tenants', function (Blueprint $table) {
            $table->comment('販売先（テナント）マスタ');

            // システム識別子
            $table->unsignedBigInteger('tenant_id')
                ->primary()
                ->comment('内部用連番 PK');
            $table->uuid('public_id')
                ->unique()
                ->default(DB::raw('gen_random_uuid()'))
                ->comment('外部公開用 UUID v4');

            // ビジネス識別子
            $table->string('tenant_code')
                ->unique()
                ->comment('テナントコード（外部公開用）');
            $table->string('tenant_name')
                ->comment('テナント名（会社名）');
            $table->string('sys_organization_code', 12)
                ->comment('m5 システム組織コード');

            // 属性
            $table->string('customers_sys_organization_code', 12)
                ->comment('m5 顧客システム組織コード');
            $table->string('remarks')->nullable()
                ->comment('備考');

            // 監査系
            $table->timestamp('created_at')->useCurrent()
                ->comment('作成日時');
            $table->timestamp('updated_at')->useCurrent()
                ->comment('更新日時');
            $table->timestamp('deleted_at')->nullable()
                ->comment('削除日時');
        });

        // ID列にIDENTITYを追加する
        DB::statement("ALTER TABLE tenants ALTER COLUMN tenant_id ADD GENERATED BY DEFAULT AS IDENTITY");
        // パーシャルインデックス（論理削除されていない行のみ）
        DB::statement("CREATE INDEX idx_tenants_deleted_null ON tenants (tenant_id) WHERE deleted_at IS NULL");
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('tenants');
    }
};
