<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('user_options', function (Blueprint $table) {
            $table->comment('ユーザー設定テーブル');

            // システム識別子
            $table->unsignedBigInteger('user_option_id')
                ->primary()
                ->comment('内部用連番 PK');

            $table->uuid('public_id')
                ->unique()
                ->default(DB::raw('gen_random_uuid()'))
                ->comment('外部公開用 UUID v4');

            // ビジネス識別子
            $table->unsignedBigInteger('tenant_id')->nullable()->comment('テナントID');
            $table->unsignedBigInteger('customer_id')->nullable()->comment('顧客ID');
            $table->unsignedBigInteger('service_id')->nullable()->comment('サービスID');

            $table->string('sys_user_code', 12)->comment('対応する m5 システムユーザーコード');
            $table->string('sys_organization_code', 12)->comment('所属組織の m5 システム組織コード');
            $table->boolean('platform_user')->nullable()->comment('プラットフォームユーザー識別');

            // 属性
            $table->text('user_icon_url')->nullable()->comment('ユーザーアイコン画像URL');
            $table->char('country_code_alpha3', 3)->default('JPN')->comment('ユーザーが設定する国・地域コード');
            $table->char('language_code', 3)->default('jpn')->comment('ユーザーが設定する言語コード');
            $table->unsignedBigInteger('time_zone_id')->comment('選択されたタイムゾーン (time_zones FK)');
            $table->char('date_format', 8)->default('yyyymmdd')->comment('日付表示形式 (yyyymmdd / mmddyyyy / ddmmyyyy)');
            $table->string('phone_number')->nullable()->comment('電話番号');
            $table->string('remarks')->nullable()->comment('備考');

            // 監査
            $table->timestamp('created_at')->useCurrent()->comment('作成日時');
            $table->timestamp('updated_at')->useCurrent()->comment('更新日時');
            $table->timestamp('deleted_at')->nullable()->comment('削除日時');

            // 外部キー
            $table->foreign('time_zone_id', 'fk_time_zone')
                ->references('time_zone_id')
                ->on('time_zones')
                ->onUpdate('restrict')
                ->onDelete('restrict');

            $table->index('sys_user_code');
        });

        // ID列にIDENTITYを追加する
        DB::statement("ALTER TABLE user_options ALTER COLUMN user_option_id ADD GENERATED BY DEFAULT AS IDENTITY");
        // CHECK制約（date_format 限定値）
        DB::statement("ALTER TABLE user_options ADD CONSTRAINT chk_date_format CHECK (date_format IN ('yyyymmdd', 'mmddyyyy', 'ddmmyyyy'))");
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('user_options');
    }
};
