<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('company_role_translations', function (Blueprint $table) {
            $table->comment('法人役割の多言語訳');

            // システム識別子
            $table->unsignedBigInteger('company_role_translation_id')
                ->primary()
                ->comment('内部用連番 PK');

            // ビジネス識別子
            $table->unsignedBigInteger('company_role_id')
                ->comment('参照先 company_role_id');
            $table->char('language_code', 3)
                ->comment('言語コード (ISO-639-3)');

            // 属性
            $table->string('company_role_name')
                ->comment('翻訳後の役割名');
            $table->string('company_role_short_name')->nullable()
                ->comment('翻訳後の略称');
            $table->string('remarks')->nullable()
                ->comment('備考');

            // 監査系
            $table->timestamp('created_at')->useCurrent()
                ->comment('レコード作成日時');
            $table->timestamp('updated_at')->useCurrent()
                ->comment('レコード更新日時');
            $table->timestamp('deleted_at')->nullable()
                ->comment('レコード削除日時');

            // 複合ユニーク制約
            $table->unique(['company_role_id', 'language_code']);

            // 外部キー制約
            $table->foreign('company_role_id')
                ->references('company_role_id')
                ->on('company_roles')
                ->onUpdate('cascade')
                ->onDelete('cascade');
        });

        // ID列にIDENTITYを追加する
        DB::statement("ALTER TABLE company_role_translations ALTER COLUMN company_role_translation_id ADD GENERATED BY DEFAULT AS IDENTITY");
        // 論理削除されていないデータのみを対象にするパーシャルインデックス
        DB::statement("CREATE INDEX idx_crt_deleted_null ON company_role_translations (company_role_translation_id) WHERE deleted_at IS NULL");
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('company_role_translations');
    }
};
