<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('dd_companies', function (Blueprint $table) {
            $table->comment('デューデリジェンス法人テーブル');

            // システム識別子
            $table->unsignedBigInteger('dd_company_id')
                ->primary()
                ->comment('内部用連番 PK');
            $table->uuid('public_id')
                ->unique()
                ->default(DB::raw('gen_random_uuid()'))
                ->comment('外部公開用 UUID v4');

            // 属性
            $table->unsignedBigInteger('tenant_id')
                ->comment('所属テナントID');
            $table->unsignedBigInteger('dd_entity_id')
                ->unique()
                ->comment('DDエンティティID');

            $table->string('company_name')
                ->comment('法人名称');

            $table->string('nta_corporate_number')->nullable()
                ->comment('国税庁法人番号');
            $table->char('location_code_alpha3', 3)->nullable()
                ->comment('所在地の国・地域');
            $table->integer('founded_year')->nullable()
                ->comment('設立年');
            $table->boolean('is_listed')->nullable()
                ->comment('上場区分');
            $table->integer('employee_count')->nullable()
                ->comment('従業員数');
            $table->char('capital_currency', 3)->nullable()
                ->comment('資本金通貨');
            $table->decimal('capital_amount', 18, 2)->nullable()
                ->comment('資本金金額');
            $table->text('website_jp')->nullable()
                ->comment('Webサイト（日）');
            $table->text('website_en')->nullable()
                ->comment('Webサイト（英）');

            $table->text('remarks')->nullable()
                ->comment('備考');

            // 監査系
            $table->timestamp('created_at')->useCurrent()
                ->comment('レコード作成日時');
            $table->timestamp('updated_at')->useCurrent()
                ->comment('レコード更新日時');
            $table->timestamp('deleted_at')->nullable()
                ->comment('レコード削除日時');

            // 外部キー
            $table->foreign('dd_entity_id')
                ->references('dd_entity_id')
                ->on('dd_entities')
                ->onUpdate('cascade')
                ->onDelete('cascade');

            $table->foreign('tenant_id')
                ->references('tenant_id')
                ->on('tenants')
                ->onUpdate('cascade')
                ->onDelete('cascade');

            $table->foreign('location_code_alpha3')
                ->references('country_code_alpha3')
                ->on('country_regions')
                ->onUpdate('cascade')
                ->onDelete('restrict');
        });

        // ID列にIDENTITYを追加する
        DB::statement("ALTER TABLE dd_companies ALTER COLUMN dd_company_id ADD GENERATED BY DEFAULT AS IDENTITY");
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('dd_companies');
    }
};
