<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('dd_relations', function (Blueprint $table) {
            $table->comment('デューデリジェンス関係性テーブル');

            // システム識別子
            $table->unsignedBigInteger('dd_relation_id')
                ->primary()
                ->comment('内部用連番（PK）');
            $table->uuid('public_id')
                ->unique()
                ->default(DB::raw('gen_random_uuid()'))
                ->comment('外部公開用 UUID v4');

            // 属性
            $table->unsignedBigInteger('tenant_id')
                ->comment('所属テナントID');
            $table->unsignedBigInteger('dd_case_id')
                ->comment('DDケースID');

            $table->unsignedBigInteger('dd_entity_id')
                ->comment('DDエンティティID');

            $table->string('dd_relation_type')
                ->default('dd_relation')
                ->comment('DD関係性種別タイプ');
            $table->string('dd_relation_code')
                ->comment('DD関係性種別コード');

            $table->decimal('shareholding_ratio', 3, 3)->nullable()
                ->comment('持株比率');

            $table->string('dd_relation_status')
                ->comment('ステータス：CREATE,UPDATE,DELETE');
            $table->boolean('is_confirmed')->nullable()
                ->comment('確定状態：提出・再鑑・承認完了まではFALSE');

            $table->text('remarks')->nullable()
                ->comment('備考');

            // 監査系
            $table->timestamp('created_at')->useCurrent()
                ->comment('レコード作成日時');
            $table->timestamp('updated_at')->useCurrent()
                ->comment('レコード更新日時');
            $table->timestamp('deleted_at')->nullable()
                ->comment('レコード削除日時');

            // 外部キー
            $table->foreign('tenant_id')
                ->references('tenant_id')
                ->on('tenants')
                ->onUpdate('cascade')
                ->onDelete('cascade');

            $table->foreign('dd_case_id')
                ->references('dd_case_id')
                ->on('dd_cases')
                ->onUpdate('cascade')
                ->onDelete('cascade');

            $table->foreign('dd_entity_id')
                ->references('dd_entity_id')
                ->on('dd_entities')
                ->onUpdate('cascade')
                ->onDelete('cascade');

            $table->foreign(['dd_relation_type', 'dd_relation_code'])
                ->references(['selection_item_type', 'selection_item_code'])
                ->on('selection_items')
                ->onUpdate('cascade')
                ->onDelete('restrict');
        });

        // ID列にIDENTITYを追加する
        DB::statement("ALTER TABLE dd_relations ALTER COLUMN dd_relation_id ADD GENERATED BY DEFAULT AS IDENTITY");
        // CHECK制約
        DB::statement("ALTER TABLE dd_relations ADD CONSTRAINT chk_dd_relation_type CHECK (dd_relation_type = 'dd_relation')");
        DB::statement("ALTER TABLE dd_relations ADD CONSTRAINT chk_dd_relation_status CHECK (dd_relation_status IN ('CREATE','UPDATE','DELETE'))");
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('dd_relations');
    }
};
