<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('dd_individuals', function (Blueprint $table) {
            $table->comment('デューデリジェンス個人テーブル');

            // システム識別子
            $table->unsignedBigInteger('dd_individual_id')
                ->primary()
                ->comment('内部用連番 PK');
            $table->uuid('public_id')
                ->unique()
                ->default(DB::raw('gen_random_uuid()'))
                ->comment('外部公開用 UUID v4');

            // 属性
            $table->unsignedBigInteger('tenant_id')
                ->comment('所属テナント ID（必須）');
            $table->unsignedBigInteger('dd_entity_id')
                ->unique()
                ->comment('親テーブル dd_entities の PK/FK');

            $table->string('full_name')
                ->comment('フルネーム');
            $table->string('first_name')->nullable()
                ->comment('名');
            $table->string('middle_name')->nullable()
                ->comment('ミドルネーム');
            $table->string('last_name')->nullable()
                ->comment('姓');

            $table->string('position')->nullable()
                ->comment('役職');

            $table->char('nationality_code_alpha3', 3)->nullable()
                ->comment('国籍');
            $table->string('gender_type')
                ->default('gender')
                ->comment('性別種別');
            $table->string('gender_code')
                ->comment('性別コード');
            $table->date('date_of_birth')->nullable()
                ->comment('生年月日');
            $table->string('place_of_birth')->nullable()
                ->comment('出身地');

            $table->text('remarks')->nullable()
                ->comment('備考');

            // 監査系
            $table->timestamp('created_at')->useCurrent()
                ->comment('レコード作成日時');
            $table->timestamp('updated_at')->useCurrent()
                ->comment('レコード更新日時');
            $table->timestamp('deleted_at')->nullable()
                ->comment('レコード削除日時');

            // 外部キー
            $table->foreign('dd_entity_id')
                ->references('dd_entity_id')
                ->on('dd_entities')
                ->onUpdate('cascade')
                ->onDelete('cascade');

            $table->foreign('tenant_id')
                ->references('tenant_id')
                ->on('tenants')
                ->onUpdate('cascade')
                ->onDelete('cascade');

            $table->foreign('nationality_code_alpha3')
                ->references('country_code_alpha3')
                ->on('country_regions')
                ->onUpdate('cascade')
                ->onDelete('restrict');

            $table->foreign(['gender_type', 'gender_code'])
                ->references(['selection_item_type', 'selection_item_code'])
                ->on('selection_items')
                ->onUpdate('cascade')
                ->onDelete('restrict');
        });

        // ID列にIDENTITYを追加する
        DB::statement("ALTER TABLE dd_individuals ALTER COLUMN dd_individual_id ADD GENERATED BY DEFAULT AS IDENTITY");
        // CHECK制約
        DB::statement("ALTER TABLE dd_individuals ADD CONSTRAINT chk_gender_type CHECK (gender_type = 'gender')");
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('dd_individuals');
    }
};
