components:
  parameters:
    DisplayPageNumber:
      in: query
      name: page
      required: true
      schema:
        type: integer
        minimum: 1
      description: 表示するページ番号
    DisplayedResults:
      in: query
      name: displayed
      required: false
      schema:
        type: integer
        minimum: 10
      description: 1ページに表示する件数
    AcceptLanguage:
      in: header
      name: Accept-Language
      schema:
        type: string
      description:
        |-
        リクエストの言語を指定します。
        例: eng, jpn
