services:
  apache:
    build:
        context: ../../../
        dockerfile: ./infra/docker/develop2/apache/Dockerfile
    container_name: dbo-dd-web
    ports:
      - 3000:3000
    volumes:
    - ../../../:/var/www/html
    - ./apache/conf/httpd.conf:/usr/local/apache2/conf/httpd.conf
    depends_on:
      - php-fpm
  php-fpm:
    build:
        context: ../../../
        dockerfile: ./infra/docker/develop2/php/Dockerfile
    container_name: dbo-dd-app
    volumes:
    - ../../../:/var/www/html
volumes:
  public_html:
