services:
  apache:
    image: httpd:2.4
    container_name: apache
    ports:
      - 3000:80
    volumes:
    - ../../../:/var/www/html
    - .infra/docker/develop/apache/conf/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro
    depends_on:
      - php-fpm
  php-fpm:
    build:
        context: ../../../
        dockerfile: ./infra/docker/develop/php/Dockerfile
    container_name: php_fpm
    volumes:
    - ../../../:/var/www/html
volumes:
  public_html:
